### ISSUE TITLE
I need some help to add MpChart to my project

### ISSUE THREAD

**Issue by Miladhsp** [fatemeh2sh/ReminderApp#7]
Can you send me a sample code to use MpChart?

I need this code to use in my project
Thankful

Of course with this appearance  -->
![MpChart](https://user-images.githubusercontent.com/69514897/104365503-4f76b100-552d-11eb-9f8a-4bbad6afaeaf.jpg)

**Comment by fatemeh2sh** [comment]
> Can you send me a sample code to use MpChart?
> 
> I need this code to use in my project
> Thankful
> 
> Of course with this appearance -->
> ![MpChart](https://user-images.githubusercontent.com/69514897/104365503-4f76b100-552d-11eb-9f8a-4bbad6afaeaf.jpg)

hi,
i didnt use this chart in my project.
